server:
  dockerfile: $PWD/server/Dockerfile
  build: ./server
  links:
    - redis
    - mysql
  ports:
    - "8000:8000"
  volumes:
    - $PWD/projects:/home/ubuntu/projects
  environment:
    - TERM=xterm
    - REDIS_PORT=6379
    - REDIS_HOST=redis
    - DEPLOY_ENV=local
    - MYSQL_HOST=mysql
    - MYSQL_PORT=3306
    - MYSQL_DATABASE=docker
    - MYSQL_USERNAME=docker
    - MYSQL_PASSWORD=docker
    - MYSQL_ROOT_PASSWORD=lecaoquochung

nginx:
  dockerfile: $PWD/server/nginxDockerfile
  build: ./server
  links:
    - server
  ports:
    - "80:80"

mysql:
  dockerfile: $PWD/db/Dockerfile
  build: ./db
  ports:
    - "3306:3306"

redis:
  image: redis
  ports:
    - "6379:6379"
