docker:
  dockerfile: Dockerfile
  build: .
  links:
    - redis
    - mysql
  ports:
    - "9000:9000"
  volumes:
    - ./projects:/home/ubuntu/projects
  environment:
    - REDIS_PORT=6379
    - REDIS_HOST=redis
    - DEPLOY_ENV=local
    - DB_HOST=mysql
    - DB_NAME=docker
    - DB_PORT=3306
    - DB_USERNAME=docker
    - DB_PASSWORD=lecaoquochung

redis:
  image: redis
  ports:
    - "6379:6379"

mysql:
  build: ./db
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWOR=lecaoquochung
    - MYSQL_DATABASE=docker
    - MYSQL_USER=docker
    - MYSQL_PASSWORD=docker
